# Jekyll
markdown: redcarpet
pygments: true

# HPSTR
title: Codeweaver's Keyboard
description: Where I muse on code and various other random things
disqus_shortname: atomicrat2552
url: http://blog.codeweaver.so

owner:
  name: berwyn
  avatar: avatar.png
  bio: 'Software Engineer, Gopher, Dartisan, Android Entusiest. Lover of good design, beautiful UX, art, games and small pastel-coloured horses.'
  email: berwyn.codeweaver@gmail.com
  github: berwyn
  twitter: _berwyn_

timezone: America/Denver
future: true
paginate: 5
permalink: /:categories/:title/

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]